apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 047385030300.dkr.ecr.us-east-1.amazonaws.com/gateway:17289209863e9aef7f093262f46fe39d1fbfc56e
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3001"
            - name: AUTH_SERVICE_URL
              value: "http://auth:3002"
            - name: PRODUCTS_SERVICE_URL
              value: "http://product-service:3003"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:3004"
            - name: ORDERS_SERVICE_URL
              value: "http://orders:3005"
            - name: USERS_SERVICE_URL
              value: "http://user-service:3006"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: boutique
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http   
      protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP

