apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: 047385030300.dkr.ecr.us-east-1.amazonaws.com/orders:17289209863e9aef7f093262f46fe39d1fbfc56e
          ports:
            - containerPort: 3005
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3005"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: ORDERS_DB_URL
            - name: PRODUCTS_SERVICE_URL
              value: "http://product-service:3003"

---

apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: boutique
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP
